version: '3.8'

services:
  bananzza-postgres:
    image: postgres:14
    container_name: bananzza
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data
    networks:
      - goapp-network

  lasciva-postgres:
    image: postgres:14
    container_name: lasciva
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lasciva
    ports:
      - "5433:5432"  # Пробрасываем на другой порт на хосте
    volumes:
      - pgdata2:/var/lib/postgresql/data
    networks:
      - goapp-network

  wisteria-postgres:
    image: postgres:14
    container_name: wisteria
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wisteria
    ports:
      - "5434:5432"  # Пробрасываем на другой порт на хосте
    volumes:
      - pgdata3:/var/lib/postgresql/data
    networks:
      - goapp-network

  bananzza-gomarket:
    build: .
    restart: on-failure
    depends_on:
      bananzza-postgres:
        condition: service_healthy
    env_file:
      - env/bananzza.env


volumes:
  pgdata1:
  pgdata2:
  pgdata3:

networks:
  goapp-network:
    driver: bridge
