wildberries:
  ##bananzza
  api_key: "eyJhbGciOiJFUzI1NiIsImtpZCI6IjIwMjUwMjE3djEiLCJ0eXAiOiJKV1QifQ.eyJlbnQiOjEsImV4cCI6MTc1NTU2ODk1MiwiaWQiOiIwMTk1MTQzNy1iZGVlLTcxMmItYTljYi04MWVmOTZkMGFlY2QiLCJpaWQiOjUzNjU3NjI4LCJvaWQiOjEwODA1MTYsInMiOjY2LCJzaWQiOiI3YWQ0MzEzYy0zMzIyLTQ5MjYtOWExNi01MTE3OTJhNDIxNWUiLCJ0IjpmYWxzZSwidWlkIjo1MzY1NzYyOH0.B7vWs10wxkmE1-RIZ5KwAbovsZhDg0IwoB4HOcX2nkAMBukt1Qie19V06Dwv8OnODJ3X9dsBWet3SR8E4pHEXQ"

  ##wisteria
  #api_key: "eyJhbGciOiJFUzI1NiIsImtpZCI6IjIwMjQxMDE2djEiLCJ0eXAiOiJKV1QifQ.eyJlbnQiOjEsImV4cCI6MTc0Njc1NjkwOCwiaWQiOiIwMTkzMDZmYS1hMTIxLTc5MTEtYTU3NS1hNzM3MDgxMGY0MGIiLCJpaWQiOjYyOTQ5MDczLCJvaWQiOjYxNDkzOSwicyI6ODIsInNpZCI6ImM0OTdkMDViLWVjNWUtNGFkOC1iNGQ5LTU4MDZmMTZlNDk5MiIsInQiOmZhbHNlLCJ1aWQiOjYyOTQ5MDczfQ.Ojv8yBaWTPV1IpSwsB201CSiS288ulOo__Kg9KCqViEFCE9JA0mkED5zEDT12_uD4zsJwEHvySm8_jGAUtYguw"

  ##lasciva
  #api_key: "eyJhbGciOiJFUzI1NiIsImtpZCI6IjIwMjUwMTIwdjEiLCJ0eXAiOiJKV1QifQ.eyJlbnQiOjEsImV4cCI6MTc1NDAwNjYyMywiaWQiOiIwMTk0YjcxOC03ZWQ5LTc3N2MtOTUzOS04NTE5MzAwOGZiMWMiLCJpaWQiOjYzNjcwMTI1LCJvaWQiOjQ0NTI5NCwicyI6NzkzNCwic2lkIjoiNTJkZWRlZDUtYmU0OC00MjBiLTlmODYtZjFmZjcwMmZkZjY1IiwidCI6ZmFsc2UsInVpZCI6NjM2NzAxMjV9.fQ3hsTVEd5QcMuRQk20XqWh0XmdmvssHu5eSU1N8H9PP7ofunwViT2vtq1eYLr4-7wiQ7R4l1lPxUw21KO2Taw"
  default_values:
    package-height: 20
    package-width: 20
    package-length: 30
  brands:
    banned:
      - GVIBE
      - HOT
      - HOT PRODUCTION
      - INDEEP
      - JUJU
      - JULEJU
      - LELO
      - LOLA GAMES
      - LOLA TOYS
      - LOVENSE
      - MY.SIZE
      - ON
      - PLEASURE LAB
      - Prime Products
      - RUF
      - SEXY LIFE
      - SHIATSU
      - VIAMAX INTERNATIONAL
      - VITALIS
      - WE-VIBE
      - Молот Тора
      - Товары без упаковки
      - ФЛЕШНАШ
  identity:
    code : 1366

postgres:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  db_name: "postgres"
